export type TimeZone = keyof typeof timeZoneData;

export const timeZoneData = {
  'Pacific/Niue': {
    name: 'Pacific/Niue',
    offset: -660,
    alternativeName: 'Niue Time',
    raw: '-11:00 Niue Time - Alofi',
    countryName: 'Niue',
    dstOffset: -660,
  },
  'Pacific/Midway': {
    name: 'Pacific/Midway',
    offset: -660,
    alternativeName: 'Samoa Time',
    raw: '-11:00 Samoa Time - Midway',
    countryName: 'United States Minor Outlying Islands',
    dstOffset: -660,
  },
  'Pacific/Pago_Pago': {
    name: 'Pacific/Pago_Pago',
    offset: -660,
    alternativeName: 'Samoa Time',
    raw: '-11:00 Samoa Time - Pago Pago',
    countryName: 'American Samoa',
    dstOffset: -660,
  },
  'Pacific/Rarotonga': {
    name: 'Pacific/Rarotonga',
    offset: -600,
    alternativeName: 'Cook Islands Time',
    raw: '-10:00 Cook Islands Time - Avarua',
    countryName: 'Cook Islands',
    dstOffset: -600,
  },
  'America/Adak': {
    name: 'America/Adak',
    offset: -600,
    alternativeName: 'Hawaii-Aleutian Time',
    raw: '-10:00 Hawaii-Aleutian Time - Adak',
    countryName: 'United States',
    dstOffset: -540,
  },
  'Pacific/Honolulu': {
    name: 'Pacific/Honolulu',
    offset: -600,
    alternativeName: 'Hawaii-Aleutian Time',
    raw: '-10:00 Hawaii-Aleutian Time - Honolulu, East Honolulu, Pearl City, Hilo',
    countryName: 'United States',
    dstOffset: -600,
  },
  'Pacific/Tahiti': {
    name: 'Pacific/Tahiti',
    offset: -600,
    alternativeName: 'Tahiti Time',
    raw: '-10:00 Tahiti Time - Faaa, Papeete, Punaauia',
    countryName: 'French Polynesia',
    dstOffset: -600,
  },
  'Pacific/Marquesas': {
    name: 'Pacific/Marquesas',
    offset: -570,
    alternativeName: 'Marquesas Time',
    raw: '-09:30 Marquesas Time - Marquesas',
    countryName: 'French Polynesia',
    dstOffset: -570,
  },
  'America/Anchorage': {
    name: 'America/Anchorage',
    offset: -540,
    alternativeName: 'Alaska Time',
    raw: '-09:00 Alaska Time - Anchorage, Juneau, Fairbanks, Eagle River',
    countryName: 'United States',
    dstOffset: -480,
  },
  'Pacific/Gambier': {
    name: 'Pacific/Gambier',
    offset: -540,
    alternativeName: 'Gambier Time',
    raw: '-09:00 Gambier Time - Gambier',
    countryName: 'French Polynesia',
    dstOffset: -540,
  },
  'America/Los_Angeles': {
    name: 'America/Los_Angeles',
    offset: -480,
    alternativeName: 'Pacific Time',
    raw: '-08:00 Pacific Time - Los Angeles, San Diego, San Jose, San Francisco',
    countryName: 'United States',
    dstOffset: -420,
  },
  'America/Tijuana': {
    name: 'America/Tijuana',
    offset: -480,
    alternativeName: 'Pacific Time',
    raw: '-08:00 Pacific Time - Tijuana, Mexicali, Ensenada, Rosarito',
    countryName: 'Mexico',
    dstOffset: -420,
  },
  'America/Vancouver': {
    name: 'America/Vancouver',
    offset: -480,
    alternativeName: 'Pacific Time',
    raw: '-08:00 Pacific Time - Vancouver, Surrey, Okanagan, Victoria',
    countryName: 'Canada',
    dstOffset: -420,
  },
  'Pacific/Pitcairn': {
    name: 'Pacific/Pitcairn',
    offset: -480,
    alternativeName: 'Pitcairn Time',
    raw: '-08:00 Pitcairn Time - Adamstown',
    countryName: 'Pitcairn',
    dstOffset: -480,
  },
  'America/Mazatlan': {
    name: 'America/Mazatlan',
    offset: -420,
    alternativeName: 'Mexican Pacific Time',
    raw: '-07:00 Mexican Pacific Time - Culiacán, Hermosillo, Mazatlán, Tepic',
    countryName: 'Mexico',
    dstOffset: -360,
  },
  'America/Edmonton': {
    name: 'America/Edmonton',
    offset: -420,
    alternativeName: 'Mountain Time',
    raw: '-07:00 Mountain Time - Calgary, Edmonton, Red Deer, Sherwood Park',
    countryName: 'Canada',
    dstOffset: -360,
  },
  'America/Denver': {
    name: 'America/Denver',
    offset: -420,
    alternativeName: 'Mountain Time',
    raw: '-07:00 Mountain Time - Denver, El Paso, Albuquerque, Colorado Springs',
    countryName: 'United States',
    dstOffset: -360,
  },
  'America/Phoenix': {
    name: 'America/Phoenix',
    offset: -420,
    alternativeName: 'Mountain Time',
    raw: '-07:00 Mountain Time - Phoenix, Tucson, Mesa, Chandler',
    countryName: 'United States',
    dstOffset: -420,
  },
  'America/Whitehorse': {
    name: 'America/Whitehorse',
    offset: -420,
    alternativeName: 'Yukon Time',
    raw: '-07:00 Yukon Time - Whitehorse, Fort St. John, Creston, Dawson',
    countryName: 'Canada',
    dstOffset: -420,
  },
  'America/Belize': {
    name: 'America/Belize',
    offset: -360,
    alternativeName: 'Central Time',
    raw: '-06:00 Central Time - Belize City, San Ignacio, San Pedro, Orange Walk',
    countryName: 'Belize',
    dstOffset: -360,
  },
  'America/Chicago': {
    name: 'America/Chicago',
    offset: -360,
    alternativeName: 'Central Time',
    raw: '-06:00 Central Time - Chicago, Houston, San Antonio, Dallas',
    countryName: 'United States',
    dstOffset: -300,
  },
  'America/Guatemala': {
    name: 'America/Guatemala',
    offset: -360,
    alternativeName: 'Central Time',
    raw: '-06:00 Central Time - Guatemala City, Mixco, Villa Nueva, Cobán',
    countryName: 'Guatemala',
    dstOffset: -360,
  },
  'America/Managua': {
    name: 'America/Managua',
    offset: -360,
    alternativeName: 'Central Time',
    raw: '-06:00 Central Time - Managua, León, Masaya, Chinandega',
    countryName: 'Nicaragua',
    dstOffset: -360,
  },
  'America/Mexico_City': {
    name: 'America/Mexico_City',
    offset: -360,
    alternativeName: 'Central Time',
    raw: '-06:00 Central Time - Mexico City, Iztapalapa, Puebla, Ecatepec de Morelos',
    countryName: 'Mexico',
    dstOffset: -300,
  },
  'America/Matamoros': {
    name: 'America/Matamoros',
    offset: -360,
    alternativeName: 'Central Time',
    raw: '-06:00 Central Time - Reynosa, Heroica Matamoros, Nuevo Laredo, Piedras Negras',
    countryName: 'Mexico',
    dstOffset: -300,
  },
  'America/Costa_Rica': {
    name: 'America/Costa_Rica',
    offset: -360,
    alternativeName: 'Central Time',
    raw: '-06:00 Central Time - San José, Limón, San Francisco, Alajuela',
    countryName: 'Costa Rica',
    dstOffset: -360,
  },
  'America/El_Salvador': {
    name: 'America/El_Salvador',
    offset: -360,
    alternativeName: 'Central Time',
    raw: '-06:00 Central Time - San Salvador, Soyapango, San Miguel, Santa Ana',
    countryName: 'El Salvador',
    dstOffset: -360,
  },
  'America/Regina': {
    name: 'America/Regina',
    offset: -360,
    alternativeName: 'Central Time',
    raw: '-06:00 Central Time - Saskatoon, Regina, Prince Albert, Moose Jaw',
    countryName: 'Canada',
    dstOffset: -360,
  },
  'America/Tegucigalpa': {
    name: 'America/Tegucigalpa',
    offset: -360,
    alternativeName: 'Central Time',
    raw: '-06:00 Central Time - Tegucigalpa, San Pedro Sula, La Ceiba, Choloma',
    countryName: 'Honduras',
    dstOffset: -360,
  },
  'America/Winnipeg': {
    name: 'America/Winnipeg',
    offset: -360,
    alternativeName: 'Central Time',
    raw: '-06:00 Central Time - Winnipeg, Brandon, Steinbach, Kenora',
    countryName: 'Canada',
    dstOffset: -300,
  },
  'Pacific/Galapagos': {
    name: 'Pacific/Galapagos',
    offset: -360,
    alternativeName: 'Galapagos Time',
    raw: '-06:00 Galapagos Time - Galapagos',
    countryName: 'Ecuador',
    dstOffset: -360,
  },
  'America/Rio_Branco': {
    name: 'America/Rio_Branco',
    offset: -300,
    alternativeName: 'Acre Time',
    raw: '-05:00 Acre Time - Rio Branco, Cruzeiro do Sul, Sena Madureira, Eirunepé',
    countryName: 'Brazil',
    dstOffset: -300,
  },
  'America/Bogota': {
    name: 'America/Bogota',
    offset: -300,
    alternativeName: 'Colombia Time',
    raw: '-05:00 Colombia Time - Bogotá, Cali, Medellín, Barranquilla',
    countryName: 'Colombia',
    dstOffset: -300,
  },
  'America/Havana': {
    name: 'America/Havana',
    offset: -300,
    alternativeName: 'Cuba Time',
    raw: '-05:00 Cuba Time - Havana, Santiago de Cuba, Camagüey, Holguín',
    countryName: 'Cuba',
    dstOffset: -240,
  },
  'Pacific/Easter': {
    name: 'Pacific/Easter',
    offset: -360,
    alternativeName: 'Easter Island Time',
    raw: '-06:00 Easter Island Time - Easter',
    countryName: 'Chile',
    dstOffset: -300,
  },
  'America/Atikokan': {
    name: 'America/Atikokan',
    offset: -300,
    alternativeName: 'Eastern Time',
    raw: '-05:00 Eastern Time - Atikokan',
    countryName: 'Canada',
    dstOffset: -300,
  },
  'America/Cancun': {
    name: 'America/Cancun',
    offset: -300,
    alternativeName: 'Eastern Time',
    raw: '-05:00 Eastern Time - Cancún, Chetumal, Playa del Carmen, Cozumel',
    countryName: 'Mexico',
    dstOffset: -300,
  },
  'America/Grand_Turk': {
    name: 'America/Grand_Turk',
    offset: -300,
    alternativeName: 'Eastern Time',
    raw: '-05:00 Eastern Time - Cockburn Town',
    countryName: 'Turks and Caicos Islands',
    dstOffset: -240,
  },
  'America/Cayman': {
    name: 'America/Cayman',
    offset: -300,
    alternativeName: 'Eastern Time',
    raw: '-05:00 Eastern Time - George Town, West Bay',
    countryName: 'Cayman Islands',
    dstOffset: -300,
  },
  'America/Jamaica': {
    name: 'America/Jamaica',
    offset: -300,
    alternativeName: 'Eastern Time',
    raw: '-05:00 Eastern Time - Kingston, New Kingston, Spanish Town, Portmore',
    countryName: 'Jamaica',
    dstOffset: -300,
  },
  'America/Nassau': {
    name: 'America/Nassau',
    offset: -300,
    alternativeName: 'Eastern Time',
    raw: '-05:00 Eastern Time - Nassau, Lucaya, Freeport',
    countryName: 'Bahamas',
    dstOffset: -240,
  },
  'America/New_York': {
    name: 'America/New_York',
    offset: -300,
    alternativeName: 'Eastern Time',
    raw: '-05:00 Eastern Time - New York City, Brooklyn, Queens, Philadelphia',
    countryName: 'United States',
    dstOffset: -240,
  },
  'America/Panama': {
    name: 'America/Panama',
    offset: -300,
    alternativeName: 'Eastern Time',
    raw: '-05:00 Eastern Time - Panamá, San Miguelito, Juan Díaz, David',
    countryName: 'Panama',
    dstOffset: -300,
  },
  'America/Port-au-Prince': {
    name: 'America/Port-au-Prince',
    offset: -300,
    alternativeName: 'Eastern Time',
    raw: '-05:00 Eastern Time - Port-au-Prince, Carrefour, Delmas 73, Port-de-Paix',
    countryName: 'Haiti',
    dstOffset: -240,
  },
  'America/Toronto': {
    name: 'America/Toronto',
    offset: -300,
    alternativeName: 'Eastern Time',
    raw: '-05:00 Eastern Time - Toronto, Montréal, Ottawa, Mississauga',
    countryName: 'Canada',
    dstOffset: -240,
  },
  'America/Guayaquil': {
    name: 'America/Guayaquil',
    offset: -300,
    alternativeName: 'Ecuador Time',
    raw: '-05:00 Ecuador Time - Quito, Guayaquil, Cuenca, Santo Domingo de los Colorados',
    countryName: 'Ecuador',
    dstOffset: -300,
  },
  'America/Lima': {
    name: 'America/Lima',
    offset: -300,
    alternativeName: 'Peru Time',
    raw: '-05:00 Peru Time - Lima, Callao, Arequipa, Trujillo',
    countryName: 'Peru',
    dstOffset: -300,
  },
  'America/Manaus': {
    name: 'America/Manaus',
    offset: -240,
    alternativeName: 'Amazon Time',
    raw: '-04:00 Amazon Time - Manaus, Campo Grande, Cuiabá, Porto Velho',
    countryName: 'Brazil',
    dstOffset: -240,
  },
  'America/St_Kitts': {
    name: 'America/St_Kitts',
    offset: -240,
    alternativeName: 'Atlantic Time',
    raw: '-04:00 Atlantic Time - Basseterre',
    countryName: 'Saint Kitts and Nevis',
    dstOffset: -240,
  },
  'America/Blanc-Sablon': {
    name: 'America/Blanc-Sablon',
    offset: -240,
    alternativeName: 'Atlantic Time',
    raw: '-04:00 Atlantic Time - Blanc-Sablon',
    countryName: 'Canada',
    dstOffset: -240,
  },
  'America/Montserrat': {
    name: 'America/Montserrat',
    offset: -240,
    alternativeName: 'Atlantic Time',
    raw: '-04:00 Atlantic Time - Brades, Plymouth',
    countryName: 'Montserrat',
    dstOffset: -240,
  },
  'America/Barbados': {
    name: 'America/Barbados',
    offset: -240,
    alternativeName: 'Atlantic Time',
    raw: '-04:00 Atlantic Time - Bridgetown',
    countryName: 'Barbados',
    dstOffset: -240,
  },
  'America/St_Lucia': {
    name: 'America/St_Lucia',
    offset: -240,
    alternativeName: 'Atlantic Time',
    raw: '-04:00 Atlantic Time - Castries',
    countryName: 'Saint Lucia',
    dstOffset: -240,
  },
  'America/Port_of_Spain': {
    name: 'America/Port_of_Spain',
    offset: -240,
    alternativeName: 'Atlantic Time',
    raw: '-04:00 Atlantic Time - Chaguanas, Mon Repos, San Fernando, Port of Spain',
    countryName: 'Trinidad and Tobago',
    dstOffset: -240,
  },
  'America/Martinique': {
    name: 'America/Martinique',
    offset: -240,
    alternativeName: 'Atlantic Time',
    raw: '-04:00 Atlantic Time - Fort-de-France, Le Lamentin, Le Robert, Sainte-Marie',
    countryName: 'Martinique',
    dstOffset: -240,
  },
  'America/St_Barthelemy': {
    name: 'America/St_Barthelemy',
    offset: -240,
    alternativeName: 'Atlantic Time',
    raw: '-04:00 Atlantic Time - Gustavia',
    countryName: 'Saint Barthelemy',
    dstOffset: -240,
  },
  'America/Halifax': {
    name: 'America/Halifax',
    offset: -240,
    alternativeName: 'Atlantic Time',
    raw: '-04:00 Atlantic Time - Halifax, Moncton, Sydney, Dartmouth',
    countryName: 'Canada',
    dstOffset: -180,
  },
  'Atlantic/Bermuda': {
    name: 'Atlantic/Bermuda',
    offset: -240,
    alternativeName: 'Atlantic Time',
    raw: '-04:00 Atlantic Time - Hamilton',
    countryName: 'Bermuda',
    dstOffset: -180,
  },
  'America/St_Vincent': {
    name: 'America/St_Vincent',
    offset: -240,
    alternativeName: 'Atlantic Time',
    raw: '-04:00 Atlantic Time - Kingstown, Kingstown Park',
    countryName: 'Saint Vincent and the Grenadines',
    dstOffset: -240,
  },
  'America/Kralendijk': {
    name: 'America/Kralendijk',
    offset: -240,
    alternativeName: 'Atlantic Time',
    raw: '-04:00 Atlantic Time - Kralendijk',
    countryName: 'Bonaire, Saint Eustatius and Saba ',
    dstOffset: -240,
  },
  'America/Guadeloupe': {
    name: 'America/Guadeloupe',
    offset: -240,
    alternativeName: 'Atlantic Time',
    raw: '-04:00 Atlantic Time - Les Abymes, Baie-Mahault, Le Gosier, Petit-Bourg',
    countryName: 'Guadeloupe',
    dstOffset: -240,
  },
  'America/Marigot': {
    name: 'America/Marigot',
    offset: -240,
    alternativeName: 'Atlantic Time',
    raw: '-04:00 Atlantic Time - Marigot',
    countryName: 'Saint Martin',
    dstOffset: -240,
  },
  'America/Aruba': {
    name: 'America/Aruba',
    offset: -240,
    alternativeName: 'Atlantic Time',
    raw: '-04:00 Atlantic Time - Oranjestad, Tanki Leendert, San Nicolas',
    countryName: 'Aruba',
    dstOffset: -240,
  },
  'America/Lower_Princes': {
    name: 'America/Lower_Princes',
    offset: -240,
    alternativeName: 'Atlantic Time',
    raw: '-04:00 Atlantic Time - Philipsburg',
    countryName: 'Sint Maarten',
    dstOffset: -240,
  },
  'America/Tortola': {
    name: 'America/Tortola',
    offset: -240,
    alternativeName: 'Atlantic Time',
    raw: '-04:00 Atlantic Time - Road Town',
    countryName: 'British Virgin Islands',
    dstOffset: -240,
  },
  'America/Dominica': {
    name: 'America/Dominica',
    offset: -240,
    alternativeName: 'Atlantic Time',
    raw: '-04:00 Atlantic Time - Roseau',
    countryName: 'Dominica',
    dstOffset: -240,
  },
  'America/St_Thomas': {
    name: 'America/St_Thomas',
    offset: -240,
    alternativeName: 'Atlantic Time',
    raw: '-04:00 Atlantic Time - Saint Croix, Charlotte Amalie',
    countryName: 'U.S. Virgin Islands',
    dstOffset: -240,
  },
  'America/Grenada': {
    name: 'America/Grenada',
    offset: -240,
    alternativeName: 'Atlantic Time',
    raw: "-04:00 Atlantic Time - Saint George's",
    countryName: 'Grenada',
    dstOffset: -240,
  },
  'America/Antigua': {
    name: 'America/Antigua',
    offset: -240,
    alternativeName: 'Atlantic Time',
    raw: '-04:00 Atlantic Time - Saint John’s',
    countryName: 'Antigua and Barbuda',
    dstOffset: -240,
  },
  'America/Puerto_Rico': {
    name: 'America/Puerto_Rico',
    offset: -240,
    alternativeName: 'Atlantic Time',
    raw: '-04:00 Atlantic Time - San Juan, Bayamón, Carolina, Ponce',
    countryName: 'Puerto Rico',
    dstOffset: -240,
  },
  'America/Santo_Domingo': {
    name: 'America/Santo_Domingo',
    offset: -240,
    alternativeName: 'Atlantic Time',
    raw: '-04:00 Atlantic Time - Santo Domingo, Santiago de los Caballeros, Santo Domingo Oeste, Santo Domingo Este',
    countryName: 'Dominican Republic',
    dstOffset: -240,
  },
  'America/Anguilla': {
    name: 'America/Anguilla',
    offset: -240,
    alternativeName: 'Atlantic Time',
    raw: '-04:00 Atlantic Time - The Valley',
    countryName: 'Anguilla',
    dstOffset: -240,
  },
  'America/Thule': {
    name: 'America/Thule',
    offset: -240,
    alternativeName: 'Atlantic Time',
    raw: '-04:00 Atlantic Time - Thule',
    countryName: 'Greenland',
    dstOffset: -180,
  },
  'America/Curacao': {
    name: 'America/Curacao',
    offset: -240,
    alternativeName: 'Atlantic Time',
    raw: '-04:00 Atlantic Time - Willemstad',
    countryName: 'Curacao',
    dstOffset: -240,
  },
  'America/La_Paz': {
    name: 'America/La_Paz',
    offset: -240,
    alternativeName: 'Bolivia Time',
    raw: '-04:00 Bolivia Time - La Paz, Santa Cruz de la Sierra, Cochabamba, Sucre',
    countryName: 'Bolivia',
    dstOffset: -240,
  },
  'America/Guyana': {
    name: 'America/Guyana',
    offset: -240,
    alternativeName: 'Guyana Time',
    raw: '-04:00 Guyana Time - Georgetown, Linden, New Amsterdam',
    countryName: 'Guyana',
    dstOffset: -240,
  },
  'America/Caracas': {
    name: 'America/Caracas',
    offset: -240,
    alternativeName: 'Venezuela Time',
    raw: '-04:00 Venezuela Time - Caracas, Maracaibo, Maracay, Valencia',
    countryName: 'Venezuela',
    dstOffset: -240,
  },
  'America/St_Johns': {
    name: 'America/St_Johns',
    offset: -210,
    alternativeName: 'Newfoundland Time',
    raw: "-03:30 Newfoundland Time - St. John's, Mount Pearl, Corner Brook, Conception Bay South",
    countryName: 'Canada',
    dstOffset: -150,
  },
  'America/Argentina/Buenos_Aires': {
    name: 'America/Argentina/Buenos_Aires',
    offset: -180,
    alternativeName: 'Argentina Time',
    raw: '-03:00 Argentina Time - Buenos Aires, Córdoba, Rosario, Mar del Plata',
    countryName: 'Argentina',
    dstOffset: -180,
  },
  'America/Sao_Paulo': {
    name: 'America/Sao_Paulo',
    offset: -180,
    alternativeName: 'Brasilia Time',
    raw: '-03:00 Brasilia Time - São Paulo, Rio de Janeiro, Salvador, Fortaleza',
    countryName: 'Brazil',
    dstOffset: -180,
  },
  'Antarctica/Palmer': {
    name: 'Antarctica/Palmer',
    offset: -180,
    alternativeName: 'Chile Time',
    raw: '-03:00 Chile Time - Palmer, Rothera',
    countryName: 'Antarctica',
    dstOffset: -180,
  },
  'America/Punta_Arenas': {
    name: 'America/Punta_Arenas',
    offset: -180,
    alternativeName: 'Chile Time',
    raw: '-03:00 Chile Time - Punta Arenas, Puerto Natales',
    countryName: 'Chile',
    dstOffset: -180,
  },
  'America/Santiago': {
    name: 'America/Santiago',
    offset: -240,
    alternativeName: 'Chile Time',
    raw: '-04:00 Chile Time - Santiago, Puente Alto, Antofagasta, Viña del Mar',
    countryName: 'Chile',
    dstOffset: -180,
  },
  'Atlantic/Stanley': {
    name: 'Atlantic/Stanley',
    offset: -180,
    alternativeName: 'Falkland Islands Time',
    raw: '-03:00 Falkland Islands Time - Stanley',
    countryName: 'Falkland Islands',
    dstOffset: -180,
  },
  'America/Cayenne': {
    name: 'America/Cayenne',
    offset: -180,
    alternativeName: 'French Guiana Time',
    raw: '-03:00 French Guiana Time - Cayenne, Matoury, Saint-Laurent-du-Maroni, Kourou',
    countryName: 'French Guiana',
    dstOffset: -180,
  },
  'America/Asuncion': {
    name: 'America/Asuncion',
    offset: -240,
    alternativeName: 'Paraguay Time',
    raw: '-04:00 Paraguay Time - Asunción, Ciudad del Este, San Lorenzo, Capiatá',
    countryName: 'Paraguay',
    dstOffset: -180,
  },
  'America/Miquelon': {
    name: 'America/Miquelon',
    offset: -180,
    alternativeName: 'St. Pierre & Miquelon Time',
    raw: '-03:00 St. Pierre & Miquelon Time - Saint-Pierre',
    countryName: 'Saint Pierre and Miquelon',
    dstOffset: -120,
  },
  'America/Paramaribo': {
    name: 'America/Paramaribo',
    offset: -180,
    alternativeName: 'Suriname Time',
    raw: '-03:00 Suriname Time - Paramaribo, Lelydorp',
    countryName: 'Suriname',
    dstOffset: -180,
  },
  'America/Montevideo': {
    name: 'America/Montevideo',
    offset: -180,
    alternativeName: 'Uruguay Time',
    raw: '-03:00 Uruguay Time - Montevideo, Salto, Paysandú, Las Piedras',
    countryName: 'Uruguay',
    dstOffset: -180,
  },
  'America/Nuuk': {
    name: 'America/Nuuk',
    offset: -180,
    alternativeName: 'West Greenland Time',
    raw: '-03:00 West Greenland Time - Nuuk',
    countryName: 'Greenland',
    dstOffset: -120,
  },
  'America/Noronha': {
    name: 'America/Noronha',
    offset: -120,
    alternativeName: 'Fernando de Noronha Time',
    raw: '-02:00 Fernando de Noronha Time - Noronha',
    countryName: 'Brazil',
    dstOffset: -120,
  },
  'Atlantic/South_Georgia': {
    name: 'Atlantic/South_Georgia',
    offset: -120,
    alternativeName: 'South Georgia Time',
    raw: '-02:00 South Georgia Time - Grytviken',
    countryName: 'South Georgia and the South Sandwich Islands',
    dstOffset: -120,
  },
  'Atlantic/Azores': {
    name: 'Atlantic/Azores',
    offset: -60,
    alternativeName: 'Azores Time',
    raw: '-01:00 Azores Time - Ponta Delgada',
    countryName: 'Portugal',
    dstOffset: -60,
  },
  'Atlantic/Cape_Verde': {
    name: 'Atlantic/Cape_Verde',
    offset: -60,
    alternativeName: 'Cape Verde Time',
    raw: '-01:00 Cape Verde Time - Praia, Mindelo, Santa Maria, Cova Figueira',
    countryName: 'Cabo Verde',
    dstOffset: -60,
  },
  'America/Scoresbysund': {
    name: 'America/Scoresbysund',
    offset: -60,
    alternativeName: 'East Greenland Time',
    raw: '-01:00 East Greenland Time - Scoresbysund',
    countryName: 'Greenland',
    dstOffset: -60,
  },
  'Africa/Abidjan': {
    name: 'Africa/Abidjan',
    offset: 0,
    alternativeName: 'Greenwich Mean Time',
    raw: '+00:00 Greenwich Mean Time - Abidjan, Abobo, Bouaké, Korhogo',
    countryName: 'Ivory Coast',
    dstOffset: 0,
  },
  'Africa/Accra': {
    name: 'Africa/Accra',
    offset: 0,
    alternativeName: 'Greenwich Mean Time',
    raw: '+00:00 Greenwich Mean Time - Accra, Kumasi, Tamale, Takoradi',
    countryName: 'Ghana',
    dstOffset: 0,
  },
  'Africa/Bamako': {
    name: 'Africa/Bamako',
    offset: 0,
    alternativeName: 'Greenwich Mean Time',
    raw: '+00:00 Greenwich Mean Time - Bamako, Ségou, Sikasso, Mopti',
    countryName: 'Mali',
    dstOffset: 0,
  },
  'Africa/Bissau': {
    name: 'Africa/Bissau',
    offset: 0,
    alternativeName: 'Greenwich Mean Time',
    raw: '+00:00 Greenwich Mean Time - Bissau, Bafatá',
    countryName: 'Guinea-Bissau',
    dstOffset: 0,
  },
  'Africa/Conakry': {
    name: 'Africa/Conakry',
    offset: 0,
    alternativeName: 'Greenwich Mean Time',
    raw: '+00:00 Greenwich Mean Time - Camayenne, Conakry, Nzérékoré, Kindia',
    countryName: 'Guinea',
    dstOffset: 0,
  },
  'Africa/Dakar': {
    name: 'Africa/Dakar',
    offset: 0,
    alternativeName: 'Greenwich Mean Time',
    raw: '+00:00 Greenwich Mean Time - Dakar, Pikine, Touba, Thiès',
    countryName: 'Senegal',
    dstOffset: 0,
  },
  'America/Danmarkshavn': {
    name: 'America/Danmarkshavn',
    offset: 0,
    alternativeName: 'Greenwich Mean Time',
    raw: '+00:00 Greenwich Mean Time - Danmarkshavn',
    countryName: 'Greenland',
    dstOffset: 0,
  },
  'Europe/Isle_of_Man': {
    name: 'Europe/Isle_of_Man',
    offset: 0,
    alternativeName: 'Greenwich Mean Time',
    raw: '+00:00 Greenwich Mean Time - Douglas',
    countryName: 'Isle of Man',
    dstOffset: 60,
  },
  'Europe/Dublin': {
    name: 'Europe/Dublin',
    offset: 0,
    alternativeName: 'Greenwich Mean Time',
    raw: '+00:00 Greenwich Mean Time - Dublin, South Dublin, Cork, Luimneach',
    countryName: 'Ireland',
    dstOffset: 60,
  },
  'Africa/Freetown': {
    name: 'Africa/Freetown',
    offset: 0,
    alternativeName: 'Greenwich Mean Time',
    raw: '+00:00 Greenwich Mean Time - Freetown, Bo, Kenema, Koidu',
    countryName: 'Sierra Leone',
    dstOffset: 0,
  },
  'Atlantic/St_Helena': {
    name: 'Atlantic/St_Helena',
    offset: 0,
    alternativeName: 'Greenwich Mean Time',
    raw: '+00:00 Greenwich Mean Time - Jamestown',
    countryName: 'Saint Helena',
    dstOffset: 0,
  },
  'Africa/Lome': {
    name: 'Africa/Lome',
    offset: 0,
    alternativeName: 'Greenwich Mean Time',
    raw: '+00:00 Greenwich Mean Time - Lomé, Sokodé, Kara, Atakpamé',
    countryName: 'Togo',
    dstOffset: 0,
  },
  'Europe/London': {
    name: 'Europe/London',
    offset: 0,
    alternativeName: 'Greenwich Mean Time',
    raw: '+00:00 Greenwich Mean Time - London, Birmingham, Liverpool, Sheffield',
    countryName: 'United Kingdom',
    dstOffset: 60,
  },
  'Africa/Monrovia': {
    name: 'Africa/Monrovia',
    offset: 0,
    alternativeName: 'Greenwich Mean Time',
    raw: '+00:00 Greenwich Mean Time - Monrovia, Gbarnga, Kakata, Bensonville',
    countryName: 'Liberia',
    dstOffset: 0,
  },
  'Africa/Nouakchott': {
    name: 'Africa/Nouakchott',
    offset: 0,
    alternativeName: 'Greenwich Mean Time',
    raw: '+00:00 Greenwich Mean Time - Nouakchott, Nouadhibou, Néma, Kaédi',
    countryName: 'Mauritania',
    dstOffset: 0,
  },
  'Africa/Ouagadougou': {
    name: 'Africa/Ouagadougou',
    offset: 0,
    alternativeName: 'Greenwich Mean Time',
    raw: '+00:00 Greenwich Mean Time - Ouagadougou, Bobo-Dioulasso, Koudougou, Ouahigouya',
    countryName: 'Burkina Faso',
    dstOffset: 0,
  },
  'Atlantic/Reykjavik': {
    name: 'Atlantic/Reykjavik',
    offset: 0,
    alternativeName: 'Greenwich Mean Time',
    raw: '+00:00 Greenwich Mean Time - Reykjavík, Kópavogur, Hafnarfjörður, Reykjanesbær',
    countryName: 'Iceland',
    dstOffset: 0,
  },
  'Europe/Jersey': {
    name: 'Europe/Jersey',
    offset: 0,
    alternativeName: 'Greenwich Mean Time',
    raw: '+00:00 Greenwich Mean Time - Saint Helier',
    countryName: 'Jersey',
    dstOffset: 60,
  },
  'Europe/Guernsey': {
    name: 'Europe/Guernsey',
    offset: 0,
    alternativeName: 'Greenwich Mean Time',
    raw: '+00:00 Greenwich Mean Time - Saint Peter Port',
    countryName: 'Guernsey',
    dstOffset: 60,
  },
  'Africa/Sao_Tome': {
    name: 'Africa/Sao_Tome',
    offset: 0,
    alternativeName: 'Greenwich Mean Time',
    raw: '+00:00 Greenwich Mean Time - São Tomé',
    countryName: 'Sao Tome and Principe',
    dstOffset: 0,
  },
  'Africa/Banjul': {
    name: 'Africa/Banjul',
    offset: 0,
    alternativeName: 'Greenwich Mean Time',
    raw: '+00:00 Greenwich Mean Time - Serekunda, Brikama, Bakau, Banjul',
    countryName: 'Gambia',
    dstOffset: 0,
  },
  'Antarctica/Troll': {
    name: 'Antarctica/Troll',
    offset: 0,
    alternativeName: 'Greenwich Mean Time',
    raw: '+00:00 Greenwich Mean Time - Troll',
    countryName: 'Antarctica',
    dstOffset: 120,
  },
  'Atlantic/Canary': {
    name: 'Atlantic/Canary',
    offset: 0,
    alternativeName: 'Western European Time',
    raw: '+00:00 Western European Time - Las Palmas de Gran Canaria, Santa Cruz de Tenerife, La Laguna, Telde',
    countryName: 'Spain',
    dstOffset: 60,
  },
  'Europe/Lisbon': {
    name: 'Europe/Lisbon',
    offset: 0,
    alternativeName: 'Western European Time',
    raw: '+00:00 Western European Time - Lisbon, Porto, Amadora, Braga',
    countryName: 'Portugal',
    dstOffset: 60,
  },
  'Atlantic/Faroe': {
    name: 'Atlantic/Faroe',
    offset: 0,
    alternativeName: 'Western European Time',
    raw: '+00:00 Western European Time - Tórshavn',
    countryName: 'Faroe Islands',
    dstOffset: 60,
  },
  'Africa/Algiers': {
    name: 'Africa/Algiers',
    offset: 60,
    alternativeName: 'Central European Time',
    raw: '+01:00 Central European Time - Algiers, Boumerdas, Oran, Tébessa',
    countryName: 'Algeria',
    dstOffset: 60,
  },
  'Europe/Amsterdam': {
    name: 'Europe/Amsterdam',
    offset: 60,
    alternativeName: 'Central European Time',
    raw: '+01:00 Central European Time - Amsterdam, Rotterdam, The Hague, Utrecht',
    countryName: 'Netherlands',
    dstOffset: 120,
  },
  'Europe/Andorra': {
    name: 'Europe/Andorra',
    offset: 60,
    alternativeName: 'Central European Time',
    raw: '+01:00 Central European Time - Andorra la Vella, les Escaldes',
    countryName: 'Andorra',
    dstOffset: 120,
  },
  'Europe/Belgrade': {
    name: 'Europe/Belgrade',
    offset: 60,
    alternativeName: 'Central European Time',
    raw: '+01:00 Central European Time - Belgrade, Niš, Novi Sad, Zemun',
    countryName: 'Serbia',
    dstOffset: 120,
  },
  'Europe/Berlin': {
    name: 'Europe/Berlin',
    offset: 60,
    alternativeName: 'Central European Time',
    raw: '+01:00 Central European Time - Berlin, Hamburg, Munich, Köln',
    countryName: 'Germany',
    dstOffset: 120,
  },
  'Europe/Malta': {
    name: 'Europe/Malta',
    offset: 60,
    alternativeName: 'Central European Time',
    raw: '+01:00 Central European Time - Birkirkara, Qormi, Mosta, Żabbar',
    countryName: 'Malta',
    dstOffset: 120,
  },
  'Europe/Bratislava': {
    name: 'Europe/Bratislava',
    offset: 60,
    alternativeName: 'Central European Time',
    raw: '+01:00 Central European Time - Bratislava, Košice, Nitra, Prešov',
    countryName: 'Slovakia',
    dstOffset: 120,
  },
  'Europe/Brussels': {
    name: 'Europe/Brussels',
    offset: 60,
    alternativeName: 'Central European Time',
    raw: '+01:00 Central European Time - Brussels, Antwerpen, Gent, Charleroi',
    countryName: 'Belgium',
    dstOffset: 120,
  },
  'Europe/Budapest': {
    name: 'Europe/Budapest',
    offset: 60,
    alternativeName: 'Central European Time',
    raw: '+01:00 Central European Time - Budapest, Debrecen, Szeged, Pécs',
    countryName: 'Hungary',
    dstOffset: 120,
  },
  'Europe/Copenhagen': {
    name: 'Europe/Copenhagen',
    offset: 60,
    alternativeName: 'Central European Time',
    raw: '+01:00 Central European Time - Copenhagen, Århus, Odense, Aalborg',
    countryName: 'Denmark',
    dstOffset: 120,
  },
  'Europe/Gibraltar': {
    name: 'Europe/Gibraltar',
    offset: 60,
    alternativeName: 'Central European Time',
    raw: '+01:00 Central European Time - Gibraltar',
    countryName: 'Gibraltar',
    dstOffset: 120,
  },
  'Europe/Ljubljana': {
    name: 'Europe/Ljubljana',
    offset: 60,
    alternativeName: 'Central European Time',
    raw: '+01:00 Central European Time - Ljubljana, Maribor, Kranj, Celje',
    countryName: 'Slovenia',
    dstOffset: 120,
  },
  'Arctic/Longyearbyen': {
    name: 'Arctic/Longyearbyen',
    offset: 60,
    alternativeName: 'Central European Time',
    raw: '+01:00 Central European Time - Longyearbyen',
    countryName: 'Svalbard and Jan Mayen',
    dstOffset: 120,
  },
  'Europe/Luxembourg': {
    name: 'Europe/Luxembourg',
    offset: 60,
    alternativeName: 'Central European Time',
    raw: '+01:00 Central European Time - Luxembourg, Esch-sur-Alzette, Dudelange',
    countryName: 'Luxembourg',
    dstOffset: 120,
  },
  'Europe/Madrid': {
    name: 'Europe/Madrid',
    offset: 60,
    alternativeName: 'Central European Time',
    raw: '+01:00 Central European Time - Madrid, Barcelona, Valencia, Sevilla',
    countryName: 'Spain',
    dstOffset: 120,
  },
  'Europe/Monaco': {
    name: 'Europe/Monaco',
    offset: 60,
    alternativeName: 'Central European Time',
    raw: '+01:00 Central European Time - Monaco, Monte-Carlo',
    countryName: 'Monaco',
    dstOffset: 120,
  },
  'Europe/Oslo': {
    name: 'Europe/Oslo',
    offset: 60,
    alternativeName: 'Central European Time',
    raw: '+01:00 Central European Time - Oslo, Bergen, Trondheim, Stavanger',
    countryName: 'Norway',
    dstOffset: 120,
  },
  'Europe/Paris': {
    name: 'Europe/Paris',
    offset: 60,
    alternativeName: 'Central European Time',
    raw: '+01:00 Central European Time - Paris, Marseille, Lyon, Toulouse',
    countryName: 'France',
    dstOffset: 120,
  },
  'Europe/Podgorica': {
    name: 'Europe/Podgorica',
    offset: 60,
    alternativeName: 'Central European Time',
    raw: '+01:00 Central European Time - Podgorica, Nikšić, Herceg Novi, Pljevlja',
    countryName: 'Montenegro',
    dstOffset: 120,
  },
  'Europe/Prague': {
    name: 'Europe/Prague',
    offset: 60,
    alternativeName: 'Central European Time',
    raw: '+01:00 Central European Time - Prague, Brno, Ostrava, Pilsen',
    countryName: 'Czechia',
    dstOffset: 120,
  },
  'Europe/Rome': {
    name: 'Europe/Rome',
    offset: 60,
    alternativeName: 'Central European Time',
    raw: '+01:00 Central European Time - Rome, Milan, Naples, Turin',
    countryName: 'Italy',
    dstOffset: 120,
  },
  'Europe/San_Marino': {
    name: 'Europe/San_Marino',
    offset: 60,
    alternativeName: 'Central European Time',
    raw: '+01:00 Central European Time - San Marino',
    countryName: 'San Marino',
    dstOffset: 120,
  },
  'Europe/Sarajevo': {
    name: 'Europe/Sarajevo',
    offset: 60,
    alternativeName: 'Central European Time',
    raw: '+01:00 Central European Time - Sarajevo, Banja Luka, Zenica, Tuzla',
    countryName: 'Bosnia and Herzegovina',
    dstOffset: 120,
  },
  'Europe/Skopje': {
    name: 'Europe/Skopje',
    offset: 60,
    alternativeName: 'Central European Time',
    raw: '+01:00 Central European Time - Skopje, Bitola, Kumanovo, Prilep',
    countryName: 'North Macedonia',
    dstOffset: 120,
  },
  'Europe/Stockholm': {
    name: 'Europe/Stockholm',
    offset: 60,
    alternativeName: 'Central European Time',
    raw: '+01:00 Central European Time - Stockholm, Göteborg, Malmö, Uppsala',
    countryName: 'Sweden',
    dstOffset: 120,
  },
  'Europe/Tirane': {
    name: 'Europe/Tirane',
    offset: 60,
    alternativeName: 'Central European Time',
    raw: '+01:00 Central European Time - Tirana, Durrës, Elbasan, Vlorë',
    countryName: 'Albania',
    dstOffset: 120,
  },
  'Africa/Tunis': {
    name: 'Africa/Tunis',
    offset: 60,
    alternativeName: 'Central European Time',
    raw: '+01:00 Central European Time - Tunis, Sfax, Sousse, Kairouan',
    countryName: 'Tunisia',
    dstOffset: 60,
  },
  'Europe/Vaduz': {
    name: 'Europe/Vaduz',
    offset: 60,
    alternativeName: 'Central European Time',
    raw: '+01:00 Central European Time - Vaduz',
    countryName: 'Liechtenstein',
    dstOffset: 120,
  },
  'Europe/Vatican': {
    name: 'Europe/Vatican',
    offset: 60,
    alternativeName: 'Central European Time',
    raw: '+01:00 Central European Time - Vatican City',
    countryName: 'Vatican',
    dstOffset: 120,
  },
  'Europe/Vienna': {
    name: 'Europe/Vienna',
    offset: 60,
    alternativeName: 'Central European Time',
    raw: '+01:00 Central European Time - Vienna, Graz, Linz, Favoriten',
    countryName: 'Austria',
    dstOffset: 120,
  },
  'Europe/Warsaw': {
    name: 'Europe/Warsaw',
    offset: 60,
    alternativeName: 'Central European Time',
    raw: '+01:00 Central European Time - Warsaw, Łódź, Kraków, Wrocław',
    countryName: 'Poland',
    dstOffset: 120,
  },
  'Europe/Zagreb': {
    name: 'Europe/Zagreb',
    offset: 60,
    alternativeName: 'Central European Time',
    raw: '+01:00 Central European Time - Zagreb, Split, Rijeka, Osijek',
    countryName: 'Croatia',
    dstOffset: 120,
  },
  'Europe/Zurich': {
    name: 'Europe/Zurich',
    offset: 60,
    alternativeName: 'Central European Time',
    raw: '+01:00 Central European Time - Zürich, Genève, Basel, Lausanne',
    countryName: 'Switzerland',
    dstOffset: 120,
  },
  'Africa/Bangui': {
    name: 'Africa/Bangui',
    offset: 60,
    alternativeName: 'West Africa Time',
    raw: '+01:00 West Africa Time - Bangui, Bimbo, Mbaïki, Berbérati',
    countryName: 'Central African Republic',
    dstOffset: 60,
  },
  'Africa/Malabo': {
    name: 'Africa/Malabo',
    offset: 60,
    alternativeName: 'West Africa Time',
    raw: '+01:00 West Africa Time - Bata, Malabo, Ebebiyin',
    countryName: 'Equatorial Guinea',
    dstOffset: 60,
  },
  'Africa/Brazzaville': {
    name: 'Africa/Brazzaville',
    offset: 60,
    alternativeName: 'West Africa Time',
    raw: '+01:00 West Africa Time - Brazzaville, Pointe-Noire, Dolisie, Kayes',
    countryName: 'Republic of the Congo',
    dstOffset: 60,
  },
  'Africa/Porto-Novo': {
    name: 'Africa/Porto-Novo',
    offset: 60,
    alternativeName: 'West Africa Time',
    raw: '+01:00 West Africa Time - Cotonou, Abomey-Calavi, Djougou, Porto-Novo',
    countryName: 'Benin',
    dstOffset: 60,
  },
  'Africa/Douala': {
    name: 'Africa/Douala',
    offset: 60,
    alternativeName: 'West Africa Time',
    raw: '+01:00 West Africa Time - Douala, Yaoundé, Garoua, Kousséri',
    countryName: 'Cameroon',
    dstOffset: 60,
  },
  'Africa/Kinshasa': {
    name: 'Africa/Kinshasa',
    offset: 60,
    alternativeName: 'West Africa Time',
    raw: '+01:00 West Africa Time - Kinshasa, Masina, Kikwit, Mbandaka',
    countryName: 'Democratic Republic of the Congo',
    dstOffset: 60,
  },
  'Africa/Lagos': {
    name: 'Africa/Lagos',
    offset: 60,
    alternativeName: 'West Africa Time',
    raw: '+01:00 West Africa Time - Lagos, Kano, Ibadan, Port Harcourt',
    countryName: 'Nigeria',
    dstOffset: 60,
  },
  'Africa/Libreville': {
    name: 'Africa/Libreville',
    offset: 60,
    alternativeName: 'West Africa Time',
    raw: '+01:00 West Africa Time - Libreville, Port-Gentil, Franceville, Oyem',
    countryName: 'Gabon',
    dstOffset: 60,
  },
  'Africa/Luanda': {
    name: 'Africa/Luanda',
    offset: 60,
    alternativeName: 'West Africa Time',
    raw: '+01:00 West Africa Time - Luanda, N’dalatando, Huambo, Lobito',
    countryName: 'Angola',
    dstOffset: 60,
  },
  'Africa/Ndjamena': {
    name: 'Africa/Ndjamena',
    offset: 60,
    alternativeName: 'West Africa Time',
    raw: "+01:00 West Africa Time - N'Djamena, Moundou, Sarh, Abéché",
    countryName: 'Chad',
    dstOffset: 60,
  },
  'Africa/Niamey': {
    name: 'Africa/Niamey',
    offset: 60,
    alternativeName: 'West Africa Time',
    raw: '+01:00 West Africa Time - Niamey, Zinder, Maradi, Agadez',
    countryName: 'Niger',
    dstOffset: 60,
  },
  'Africa/Casablanca': {
    name: 'Africa/Casablanca',
    offset: 60,
    alternativeName: 'Western European Time',
    raw: '+00:00 Western European Time - Casablanca, Rabat, Fès, Sale',
    countryName: 'Morocco',
    dstOffset: 60,
  },
  'Africa/El_Aaiun': {
    name: 'Africa/El_Aaiun',
    offset: 60,
    alternativeName: 'Western European Time',
    raw: '+00:00 Western European Time - Laayoune, Dakhla, Boujdour',
    countryName: 'Western Sahara',
    dstOffset: 60,
  },
  'Asia/Amman': {
    name: 'Asia/Amman',
    offset: 120,
    alternativeName: 'Asia/Amman',
    raw: '+03:00 Asia/Amman - Amman, Zarqa, Irbid, Russeifa',
    countryName: 'Jordan',
    dstOffset: 180,
  },
  'Asia/Damascus': {
    name: 'Asia/Damascus',
    offset: 120,
    alternativeName: 'Asia/Damascus',
    raw: '+03:00 Asia/Damascus - Aleppo, Damascus, Homs, Ḩamāh',
    countryName: 'Syria',
    dstOffset: 180,
  },
  'Africa/Bujumbura': {
    name: 'Africa/Bujumbura',
    offset: 120,
    alternativeName: 'Central Africa Time',
    raw: '+02:00 Central Africa Time - Bujumbura, Muyinga, Gitega, Ruyigi',
    countryName: 'Burundi',
    dstOffset: 120,
  },
  'Africa/Gaborone': {
    name: 'Africa/Gaborone',
    offset: 120,
    alternativeName: 'Central Africa Time',
    raw: '+02:00 Central Africa Time - Gaborone, Francistown, Molepolole, Selebi-Phikwe',
    countryName: 'Botswana',
    dstOffset: 120,
  },
  'Africa/Harare': {
    name: 'Africa/Harare',
    offset: 120,
    alternativeName: 'Central Africa Time',
    raw: '+02:00 Central Africa Time - Harare, Bulawayo, Chitungwiza, Mutare',
    countryName: 'Zimbabwe',
    dstOffset: 120,
  },
  'Africa/Juba': {
    name: 'Africa/Juba',
    offset: 120,
    alternativeName: 'Central Africa Time',
    raw: '+02:00 Central Africa Time - Juba, Winejok, Yei, Malakal',
    countryName: 'South Sudan',
    dstOffset: 180,
  },
  'Africa/Khartoum': {
    name: 'Africa/Khartoum',
    offset: 120,
    alternativeName: 'Central Africa Time',
    raw: '+02:00 Central Africa Time - Khartoum, Omdurman, Nyala, Port Sudan',
    countryName: 'Sudan',
    dstOffset: 120,
  },
  'Africa/Kigali': {
    name: 'Africa/Kigali',
    offset: 120,
    alternativeName: 'Central Africa Time',
    raw: '+02:00 Central Africa Time - Kigali, Gisenyi, Butare, Gitarama',
    countryName: 'Rwanda',
    dstOffset: 120,
  },
  'Africa/Blantyre': {
    name: 'Africa/Blantyre',
    offset: 120,
    alternativeName: 'Central Africa Time',
    raw: '+02:00 Central Africa Time - Lilongwe, Blantyre, Mzuzu, Zomba',
    countryName: 'Malawi',
    dstOffset: 120,
  },
  'Africa/Lubumbashi': {
    name: 'Africa/Lubumbashi',
    offset: 120,
    alternativeName: 'Central Africa Time',
    raw: '+02:00 Central Africa Time - Lubumbashi, Mbuji-Mayi, Kisangani, Kananga',
    countryName: 'Democratic Republic of the Congo',
    dstOffset: 120,
  },
  'Africa/Lusaka': {
    name: 'Africa/Lusaka',
    offset: 120,
    alternativeName: 'Central Africa Time',
    raw: '+02:00 Central Africa Time - Lusaka, Kitwe, Ndola, Kabwe',
    countryName: 'Zambia',
    dstOffset: 120,
  },
  'Africa/Maputo': {
    name: 'Africa/Maputo',
    offset: 120,
    alternativeName: 'Central Africa Time',
    raw: '+02:00 Central Africa Time - Maputo, Matola, Nampula, Beira',
    countryName: 'Mozambique',
    dstOffset: 120,
  },
  'Africa/Windhoek': {
    name: 'Africa/Windhoek',
    offset: 120,
    alternativeName: 'Central Africa Time',
    raw: '+01:00 Central Africa Time - Windhoek, Rundu, Walvis Bay, Oshakati',
    countryName: 'Namibia',
    dstOffset: 120,
  },
  'Europe/Athens': {
    name: 'Europe/Athens',
    offset: 120,
    alternativeName: 'Eastern European Time',
    raw: '+02:00 Eastern European Time - Athens, Thessaloníki, Pátra, Piraeus',
    countryName: 'Greece',
    dstOffset: 180,
  },
  'Asia/Beirut': {
    name: 'Asia/Beirut',
    offset: 120,
    alternativeName: 'Eastern European Time',
    raw: '+02:00 Eastern European Time - Beirut, Ra’s Bayrūt, Tripoli, Sidon',
    countryName: 'Lebanon',
    dstOffset: 180,
  },
  'Europe/Bucharest': {
    name: 'Europe/Bucharest',
    offset: 120,
    alternativeName: 'Eastern European Time',
    raw: '+02:00 Eastern European Time - Bucharest, Sector 3, Iaşi, Sector 6',
    countryName: 'Romania',
    dstOffset: 180,
  },
  'Africa/Cairo': {
    name: 'Africa/Cairo',
    offset: 120,
    alternativeName: 'Eastern European Time',
    raw: '+02:00 Eastern European Time - Cairo, Alexandria, Giza, Shubrā al Khaymah',
    countryName: 'Egypt',
    dstOffset: 120,
  },
  'Europe/Chisinau': {
    name: 'Europe/Chisinau',
    offset: 120,
    alternativeName: 'Eastern European Time',
    raw: '+02:00 Eastern European Time - Chisinau, Tiraspol, Bălţi, Bender',
    countryName: 'Moldova',
    dstOffset: 180,
  },
  'Asia/Hebron': {
    name: 'Asia/Hebron',
    offset: 120,
    alternativeName: 'Eastern European Time',
    raw: '+02:00 Eastern European Time - East Jerusalem, Gaza, Khān Yūnis, Jabālyā',
    countryName: 'Palestinian Territory',
    dstOffset: 180,
  },
  'Europe/Helsinki': {
    name: 'Europe/Helsinki',
    offset: 120,
    alternativeName: 'Eastern European Time',
    raw: '+02:00 Eastern European Time - Helsinki, Espoo, Tampere, Oulu',
    countryName: 'Finland',
    dstOffset: 180,
  },
  'Europe/Kaliningrad': {
    name: 'Europe/Kaliningrad',
    offset: 120,
    alternativeName: 'Eastern European Time',
    raw: '+02:00 Eastern European Time - Kaliningrad, Chernyakhovsk, Sovetsk, Baltiysk',
    countryName: 'Russia',
    dstOffset: 120,
  },
  'Europe/Kyiv': {
    name: 'Europe/Kyiv',
    offset: 120,
    alternativeName: 'Eastern European Time',
    raw: '+02:00 Eastern European Time - Kyiv, Kharkiv, Donetsk, Odesa',
    countryName: 'Ukraine',
    dstOffset: 180,
  },
  'Europe/Mariehamn': {
    name: 'Europe/Mariehamn',
    offset: 120,
    alternativeName: 'Eastern European Time',
    raw: '+02:00 Eastern European Time - Mariehamn',
    countryName: 'Aland Islands',
    dstOffset: 180,
  },
  'Asia/Nicosia': {
    name: 'Asia/Nicosia',
    offset: 120,
    alternativeName: 'Eastern European Time',
    raw: '+02:00 Eastern European Time - Nicosia, Limassol, Larnaca, Stróvolos',
    countryName: 'Cyprus',
    dstOffset: 180,
  },
  'Europe/Riga': {
    name: 'Europe/Riga',
    offset: 120,
    alternativeName: 'Eastern European Time',
    raw: '+02:00 Eastern European Time - Riga, Daugavpils, Liepāja, Jelgava',
    countryName: 'Latvia',
    dstOffset: 180,
  },
  'Europe/Sofia': {
    name: 'Europe/Sofia',
    offset: 120,
    alternativeName: 'Eastern European Time',
    raw: '+02:00 Eastern European Time - Sofia, Plovdiv, Varna, Burgas',
    countryName: 'Bulgaria',
    dstOffset: 180,
  },
  'Europe/Tallinn': {
    name: 'Europe/Tallinn',
    offset: 120,
    alternativeName: 'Eastern European Time',
    raw: '+02:00 Eastern European Time - Tallinn, Tartu, Narva, Pärnu',
    countryName: 'Estonia',
    dstOffset: 180,
  },
  'Africa/Tripoli': {
    name: 'Africa/Tripoli',
    offset: 120,
    alternativeName: 'Eastern European Time',
    raw: '+02:00 Eastern European Time - Tripoli, Benghazi, Ajdabiya, Mişrātah',
    countryName: 'Libya',
    dstOffset: 120,
  },
  'Europe/Vilnius': {
    name: 'Europe/Vilnius',
    offset: 120,
    alternativeName: 'Eastern European Time',
    raw: '+02:00 Eastern European Time - Vilnius, Kaunas, Klaipėda, Šiauliai',
    countryName: 'Lithuania',
    dstOffset: 180,
  },
  'Asia/Jerusalem': {
    name: 'Asia/Jerusalem',
    offset: 120,
    alternativeName: 'Israel Time',
    raw: '+02:00 Israel Time - Jerusalem, Tel Aviv, West Jerusalem, Haifa',
    countryName: 'Israel',
    dstOffset: 180,
  },
  'Africa/Johannesburg': {
    name: 'Africa/Johannesburg',
    offset: 120,
    alternativeName: 'South Africa Time',
    raw: '+02:00 South Africa Time - Johannesburg, Cape Town, Durban, Soweto',
    countryName: 'South Africa',
    dstOffset: 120,
  },
  'Africa/Mbabane': {
    name: 'Africa/Mbabane',
    offset: 120,
    alternativeName: 'South Africa Time',
    raw: '+02:00 South Africa Time - Manzini, Mbabane, Lobamba',
    countryName: 'Eswatini',
    dstOffset: 120,
  },
  'Africa/Maseru': {
    name: 'Africa/Maseru',
    offset: 120,
    alternativeName: 'South Africa Time',
    raw: '+02:00 South Africa Time - Maseru, Mohale’s Hoek, Mafeteng, Leribe',
    countryName: 'Lesotho',
    dstOffset: 120,
  },
  'Asia/Kuwait': {
    name: 'Asia/Kuwait',
    offset: 180,
    alternativeName: 'Arabian Time',
    raw: '+03:00 Arabian Time - Al Aḩmadī, Ḩawallī, As Sālimīyah, Şabāḩ as Sālim',
    countryName: 'Kuwait',
    dstOffset: 180,
  },
  'Asia/Baghdad': {
    name: 'Asia/Baghdad',
    offset: 180,
    alternativeName: 'Arabian Time',
    raw: '+03:00 Arabian Time - Baghdad, Basrah, Al Mawşil al Jadīdah, Al Başrah al Qadīmah',
    countryName: 'Iraq',
    dstOffset: 180,
  },
  'Asia/Qatar': {
    name: 'Asia/Qatar',
    offset: 180,
    alternativeName: 'Arabian Time',
    raw: '+03:00 Arabian Time - Doha, Ar Rayyān, Umm Şalāl Muḩammad, Al Wakrah',
    countryName: 'Qatar',
    dstOffset: 180,
  },
  'Asia/Riyadh': {
    name: 'Asia/Riyadh',
    offset: 180,
    alternativeName: 'Arabian Time',
    raw: '+03:00 Arabian Time - Jeddah, Riyadh, Mecca, Medina',
    countryName: 'Saudi Arabia',
    dstOffset: 180,
  },
  'Asia/Bahrain': {
    name: 'Asia/Bahrain',
    offset: 180,
    alternativeName: 'Arabian Time',
    raw: '+03:00 Arabian Time - Manama, Al Muharraq, Ar Rifā‘, Dār Kulayb',
    countryName: 'Bahrain',
    dstOffset: 180,
  },
  'Asia/Aden': {
    name: 'Asia/Aden',
    offset: 180,
    alternativeName: 'Arabian Time',
    raw: '+03:00 Arabian Time - Sanaa, Al Ḩudaydah, Taiz, Aden',
    countryName: 'Yemen',
    dstOffset: 180,
  },
  'Africa/Addis_Ababa': {
    name: 'Africa/Addis_Ababa',
    offset: 180,
    alternativeName: 'East Africa Time',
    raw: '+03:00 East Africa Time - Addis Ababa, Gondar, Nazrēt, Desē',
    countryName: 'Ethiopia',
    dstOffset: 180,
  },
  'Indian/Antananarivo': {
    name: 'Indian/Antananarivo',
    offset: 180,
    alternativeName: 'East Africa Time',
    raw: '+03:00 East Africa Time - Antananarivo, Toamasina, Antsirabe, Mahajanga',
    countryName: 'Madagascar',
    dstOffset: 180,
  },
  'Africa/Asmara': {
    name: 'Africa/Asmara',
    offset: 180,
    alternativeName: 'East Africa Time',
    raw: '+03:00 East Africa Time - Asmara, Keren, Massawa, Assab',
    countryName: 'Eritrea',
    dstOffset: 180,
  },
  'Africa/Dar_es_Salaam': {
    name: 'Africa/Dar_es_Salaam',
    offset: 180,
    alternativeName: 'East Africa Time',
    raw: '+03:00 East Africa Time - Dar es Salaam, Mwanza, Zanzibar, Arusha',
    countryName: 'Tanzania',
    dstOffset: 180,
  },
  'Africa/Djibouti': {
    name: 'Africa/Djibouti',
    offset: 180,
    alternativeName: 'East Africa Time',
    raw: "+03:00 East Africa Time - Djibouti, 'Ali Sabieh, Tadjourah, Obock",
    countryName: 'Djibouti',
    dstOffset: 180,
  },
  'Africa/Kampala': {
    name: 'Africa/Kampala',
    offset: 180,
    alternativeName: 'East Africa Time',
    raw: '+03:00 East Africa Time - Kampala, Gulu, Lira, Mbarara',
    countryName: 'Uganda',
    dstOffset: 180,
  },
  'Indian/Mayotte': {
    name: 'Indian/Mayotte',
    offset: 180,
    alternativeName: 'East Africa Time',
    raw: '+03:00 East Africa Time - Mamoudzou, Koungou, Dzaoudzi',
    countryName: 'Mayotte',
    dstOffset: 180,
  },
  'Africa/Mogadishu': {
    name: 'Africa/Mogadishu',
    offset: 180,
    alternativeName: 'East Africa Time',
    raw: '+03:00 East Africa Time - Mogadishu, Hargeysa, Berbera, Kismayo',
    countryName: 'Somalia',
    dstOffset: 180,
  },
  'Indian/Comoro': {
    name: 'Indian/Comoro',
    offset: 180,
    alternativeName: 'East Africa Time',
    raw: '+03:00 East Africa Time - Moroni, Moutsamoudou',
    countryName: 'Comoros',
    dstOffset: 180,
  },
  'Africa/Nairobi': {
    name: 'Africa/Nairobi',
    offset: 180,
    alternativeName: 'East Africa Time',
    raw: '+03:00 East Africa Time - Nairobi, Kakamega, Mombasa, Ruiru',
    countryName: 'Kenya',
    dstOffset: 180,
  },
  'Europe/Minsk': {
    name: 'Europe/Minsk',
    offset: 180,
    alternativeName: 'Moscow Time',
    raw: "+03:00 Moscow Time - Minsk, Homyel', Mahilyow, Vitebsk",
    countryName: 'Belarus',
    dstOffset: 180,
  },
  'Europe/Moscow': {
    name: 'Europe/Moscow',
    offset: 180,
    alternativeName: 'Moscow Time',
    raw: '+03:00 Moscow Time - Moscow, Saint Petersburg, Nizhniy Novgorod, Kazan',
    countryName: 'Russia',
    dstOffset: 180,
  },
  'Europe/Simferopol': {
    name: 'Europe/Simferopol',
    offset: 180,
    alternativeName: 'Moscow Time',
    raw: '+03:00 Moscow Time - Sevastopol, Simferopol, Kerch, Yevpatoriya',
    countryName: 'Ukraine',
    dstOffset: 180,
  },
  'Antarctica/Syowa': {
    name: 'Antarctica/Syowa',
    offset: 180,
    alternativeName: 'Syowa Time',
    raw: '+03:00 Syowa Time - Syowa',
    countryName: 'Antarctica',
    dstOffset: 180,
  },
  'Europe/Istanbul': {
    name: 'Europe/Istanbul',
    offset: 180,
    alternativeName: 'Turkey Time',
    raw: '+03:00 Turkey Time - Istanbul, Ankara, İzmir, Bursa',
    countryName: 'Turkey',
    dstOffset: 180,
  },
  'Asia/Tehran': {
    name: 'Asia/Tehran',
    offset: 210,
    alternativeName: 'Iran Time',
    raw: '+03:30 Iran Time - Tehran, Mashhad, Isfahan, Karaj',
    countryName: 'Iran',
    dstOffset: 270,
  },
  'Asia/Yerevan': {
    name: 'Asia/Yerevan',
    offset: 240,
    alternativeName: 'Armenia Time',
    raw: '+04:00 Armenia Time - Yerevan, Gyumri, Vanadzor, Vagharshapat',
    countryName: 'Armenia',
    dstOffset: 240,
  },
  'Asia/Baku': {
    name: 'Asia/Baku',
    offset: 240,
    alternativeName: 'Azerbaijan Time',
    raw: '+04:00 Azerbaijan Time - Baku, Ganja, Sumqayıt, Lankaran',
    countryName: 'Azerbaijan',
    dstOffset: 240,
  },
  'Asia/Tbilisi': {
    name: 'Asia/Tbilisi',
    offset: 240,
    alternativeName: 'Georgia Time',
    raw: '+04:00 Georgia Time - Tbilisi, Kutaisi, Batumi, Sokhumi',
    countryName: 'Georgia',
    dstOffset: 240,
  },
  'Asia/Dubai': {
    name: 'Asia/Dubai',
    offset: 240,
    alternativeName: 'Gulf Time',
    raw: '+04:00 Gulf Time - Dubai, Sharjah, Abu Dhabi, Ajman City',
    countryName: 'United Arab Emirates',
    dstOffset: 240,
  },
  'Asia/Muscat': {
    name: 'Asia/Muscat',
    offset: 240,
    alternativeName: 'Gulf Time',
    raw: '+04:00 Gulf Time - Muscat, Seeb, Bawshar, ‘Ibrī',
    countryName: 'Oman',
    dstOffset: 240,
  },
  'Indian/Mauritius': {
    name: 'Indian/Mauritius',
    offset: 240,
    alternativeName: 'Mauritius Time',
    raw: '+04:00 Mauritius Time - Port Louis, Beau Bassin-Rose Hill, Vacoas, Curepipe',
    countryName: 'Mauritius',
    dstOffset: 240,
  },
  'Indian/Reunion': {
    name: 'Indian/Reunion',
    offset: 240,
    alternativeName: 'Réunion Time',
    raw: '+04:00 Réunion Time - Saint-Denis, Saint-Paul, Le Tampon, Saint-Pierre',
    countryName: 'Reunion',
    dstOffset: 240,
  },
  'Europe/Samara': {
    name: 'Europe/Samara',
    offset: 240,
    alternativeName: 'Samara Time',
    raw: '+04:00 Samara Time - Samara, Saratov, Tolyatti, Izhevsk',
    countryName: 'Russia',
    dstOffset: 240,
  },
  'Indian/Mahe': {
    name: 'Indian/Mahe',
    offset: 240,
    alternativeName: 'Seychelles Time',
    raw: '+04:00 Seychelles Time - Victoria',
    countryName: 'Seychelles',
    dstOffset: 240,
  },
  'Asia/Kabul': {
    name: 'Asia/Kabul',
    offset: 270,
    alternativeName: 'Afghanistan Time',
    raw: '+04:30 Afghanistan Time - Kabul, Herāt, Mazār-e Sharīf, Kandahār',
    countryName: 'Afghanistan',
    dstOffset: 270,
  },
  'Indian/Kerguelen': {
    name: 'Indian/Kerguelen',
    offset: 300,
    alternativeName: 'French Southern & Antarctic Time',
    raw: '+05:00 French Southern & Antarctic Time - Port-aux-Français',
    countryName: 'French Southern Territories',
    dstOffset: 300,
  },
  'Indian/Maldives': {
    name: 'Indian/Maldives',
    offset: 300,
    alternativeName: 'Maldives Time',
    raw: '+05:00 Maldives Time - Male',
    countryName: 'Maldives',
    dstOffset: 300,
  },
  'Antarctica/Mawson': {
    name: 'Antarctica/Mawson',
    offset: 300,
    alternativeName: 'Mawson Time',
    raw: '+05:00 Mawson Time - Mawson',
    countryName: 'Antarctica',
    dstOffset: 300,
  },
  'Asia/Karachi': {
    name: 'Asia/Karachi',
    offset: 300,
    alternativeName: 'Pakistan Time',
    raw: '+05:00 Pakistan Time - Karachi, Lahore, Faisalabad, Rawalpindi',
    countryName: 'Pakistan',
    dstOffset: 300,
  },
  'Asia/Dushanbe': {
    name: 'Asia/Dushanbe',
    offset: 300,
    alternativeName: 'Tajikistan Time',
    raw: '+05:00 Tajikistan Time - Dushanbe, Isfara, Istaravshan, Kŭlob',
    countryName: 'Tajikistan',
    dstOffset: 300,
  },
  'Asia/Ashgabat': {
    name: 'Asia/Ashgabat',
    offset: 300,
    alternativeName: 'Turkmenistan Time',
    raw: '+05:00 Turkmenistan Time - Ashgabat, Türkmenabat, Daşoguz, Mary',
    countryName: 'Turkmenistan',
    dstOffset: 300,
  },
  'Asia/Tashkent': {
    name: 'Asia/Tashkent',
    offset: 300,
    alternativeName: 'Uzbekistan Time',
    raw: '+05:00 Uzbekistan Time - Tashkent, Namangan, Samarkand, Andijon',
    countryName: 'Uzbekistan',
    dstOffset: 300,
  },
  'Asia/Aqtobe': {
    name: 'Asia/Aqtobe',
    offset: 300,
    alternativeName: 'West Kazakhstan Time',
    raw: '+05:00 West Kazakhstan Time - Aktobe, Kyzylorda, Oral, Atyrau',
    countryName: 'Kazakhstan',
    dstOffset: 300,
  },
  'Asia/Yekaterinburg': {
    name: 'Asia/Yekaterinburg',
    offset: 300,
    alternativeName: 'Yekaterinburg Time',
    raw: '+05:00 Yekaterinburg Time - Yekaterinburg, Chelyabinsk, Ufa, Perm',
    countryName: 'Russia',
    dstOffset: 300,
  },
  'Asia/Colombo': {
    name: 'Asia/Colombo',
    offset: 330,
    alternativeName: 'India Time',
    raw: '+05:30 India Time - Colombo, Dehiwala-Mount Lavinia, Maharagama, Jaffna',
    countryName: 'Sri Lanka',
    dstOffset: 330,
  },
  'Asia/Kolkata': {
    name: 'Asia/Kolkata',
    offset: 330,
    alternativeName: 'India Time',
    raw: '+05:30 India Time - Mumbai, Delhi, Bengaluru, Hyderābād',
    countryName: 'India',
    dstOffset: 330,
  },
  'Asia/Kathmandu': {
    name: 'Asia/Kathmandu',
    offset: 345,
    alternativeName: 'Nepal Time',
    raw: '+05:45 Nepal Time - Kathmandu, Bharatpur, Pātan, Birgañj',
    countryName: 'Nepal',
    dstOffset: 345,
  },
  'Asia/Dhaka': {
    name: 'Asia/Dhaka',
    offset: 360,
    alternativeName: 'Bangladesh Time',
    raw: '+06:00 Bangladesh Time - Dhaka, Chattogram, Khulna, Rājshāhi',
    countryName: 'Bangladesh',
    dstOffset: 360,
  },
  'Asia/Thimphu': {
    name: 'Asia/Thimphu',
    offset: 360,
    alternativeName: 'Bhutan Time',
    raw: '+06:00 Bhutan Time - Thimphu, Tsirang, Punākha, Phuntsholing',
    countryName: 'Bhutan',
    dstOffset: 360,
  },
  'Asia/Urumqi': {
    name: 'Asia/Urumqi',
    offset: 360,
    alternativeName: 'China Time',
    raw: '+06:00 China Time - Ürümqi, Shihezi, Korla, Aksu',
    countryName: 'China',
    dstOffset: 360,
  },
  'Asia/Almaty': {
    name: 'Asia/Almaty',
    offset: 360,
    alternativeName: 'East Kazakhstan Time',
    raw: '+06:00 East Kazakhstan Time - Almaty, Shymkent, Karagandy, Taraz',
    countryName: 'Kazakhstan',
    dstOffset: 360,
  },
  'Indian/Chagos': {
    name: 'Indian/Chagos',
    offset: 360,
    alternativeName: 'Indian Ocean Time',
    raw: '+06:00 Indian Ocean Time - Chagos',
    countryName: 'British Indian Ocean Territory',
    dstOffset: 360,
  },
  'Asia/Bishkek': {
    name: 'Asia/Bishkek',
    offset: 360,
    alternativeName: 'Kyrgyzstan Time',
    raw: '+06:00 Kyrgyzstan Time - Bishkek, Osh, Jalal-Abad, Karakol',
    countryName: 'Kyrgyzstan',
    dstOffset: 360,
  },
  'Asia/Omsk': {
    name: 'Asia/Omsk',
    offset: 360,
    alternativeName: 'Omsk Time',
    raw: '+06:00 Omsk Time - Omsk, Tara, Kalachinsk',
    countryName: 'Russia',
    dstOffset: 360,
  },
  'Antarctica/Vostok': {
    name: 'Antarctica/Vostok',
    offset: 360,
    alternativeName: 'Vostok Time',
    raw: '+06:00 Vostok Time - Vostok',
    countryName: 'Antarctica',
    dstOffset: 360,
  },
  'Indian/Cocos': {
    name: 'Indian/Cocos',
    offset: 390,
    alternativeName: 'Cocos Islands Time',
    raw: '+06:30 Cocos Islands Time - West Island',
    countryName: 'Cocos Islands',
    dstOffset: 390,
  },
  'Asia/Yangon': {
    name: 'Asia/Yangon',
    offset: 390,
    alternativeName: 'Myanmar Time',
    raw: '+06:30 Myanmar Time - Yangon, Mandalay, Nay Pyi Taw, Mawlamyine',
    countryName: 'Myanmar',
    dstOffset: 390,
  },
  'Indian/Christmas': {
    name: 'Indian/Christmas',
    offset: 420,
    alternativeName: 'Christmas Island Time',
    raw: '+07:00 Christmas Island Time - Flying Fish Cove',
    countryName: 'Christmas Island',
    dstOffset: 420,
  },
  'Antarctica/Davis': {
    name: 'Antarctica/Davis',
    offset: 420,
    alternativeName: 'Davis Time',
    raw: '+07:00 Davis Time - Davis',
    countryName: 'Antarctica',
    dstOffset: 420,
  },
  'Asia/Hovd': {
    name: 'Asia/Hovd',
    offset: 420,
    alternativeName: 'Hovd Time',
    raw: '+07:00 Hovd Time - Ulaangom, Khovd, Ölgii, Altai',
    countryName: 'Mongolia',
    dstOffset: 420,
  },
  'Asia/Bangkok': {
    name: 'Asia/Bangkok',
    offset: 420,
    alternativeName: 'Indochina Time',
    raw: '+07:00 Indochina Time - Bangkok, Samut Prakan, Mueang Nonthaburi, Udon Thani',
    countryName: 'Thailand',
    dstOffset: 420,
  },
  'Asia/Ho_Chi_Minh': {
    name: 'Asia/Ho_Chi_Minh',
    offset: 420,
    alternativeName: 'Indochina Time',
    raw: '+07:00 Indochina Time - Ho Chi Minh City, Da Nang, Biên Hòa, Cần Thơ',
    countryName: 'Vietnam',
    dstOffset: 420,
  },
  'Asia/Phnom_Penh': {
    name: 'Asia/Phnom_Penh',
    offset: 420,
    alternativeName: 'Indochina Time',
    raw: '+07:00 Indochina Time - Phnom Penh, Takeo, Siem Reap, Battambang',
    countryName: 'Cambodia',
    dstOffset: 420,
  },
  'Asia/Vientiane': {
    name: 'Asia/Vientiane',
    offset: 420,
    alternativeName: 'Indochina Time',
    raw: '+07:00 Indochina Time - Vientiane, Savannakhet, Pakse, Thakhèk',
    countryName: 'Laos',
    dstOffset: 420,
  },
  'Asia/Novosibirsk': {
    name: 'Asia/Novosibirsk',
    offset: 420,
    alternativeName: 'Novosibirsk Time',
    raw: '+07:00 Novosibirsk Time - Novosibirsk, Krasnoyarsk, Barnaul, Tomsk',
    countryName: 'Russia',
    dstOffset: 420,
  },
  'Asia/Jakarta': {
    name: 'Asia/Jakarta',
    offset: 420,
    alternativeName: 'Western Indonesia Time',
    raw: '+07:00 Western Indonesia Time - Jakarta, Surabaya, Bekasi, Bandung',
    countryName: 'Indonesia',
    dstOffset: 420,
  },
  'Australia/Perth': {
    name: 'Australia/Perth',
    offset: 480,
    alternativeName: 'Australian Western Time',
    raw: '+08:00 Australian Western Time - Perth, Rockingham, Mandurah, Bunbury',
    countryName: 'Australia',
    dstOffset: 480,
  },
  'Asia/Brunei': {
    name: 'Asia/Brunei',
    offset: 480,
    alternativeName: 'Brunei Darussalam Time',
    raw: '+08:00 Brunei Darussalam Time - Bandar Seri Begawan, Kuala Belait, Seria, Tutong',
    countryName: 'Brunei',
    dstOffset: 480,
  },
  'Asia/Makassar': {
    name: 'Asia/Makassar',
    offset: 480,
    alternativeName: 'Central Indonesia Time',
    raw: '+08:00 Central Indonesia Time - Makassar, Denpasar, Samarinda, Banjarmasin',
    countryName: 'Indonesia',
    dstOffset: 480,
  },
  'Asia/Macau': {
    name: 'Asia/Macau',
    offset: 480,
    alternativeName: 'China Time',
    raw: '+08:00 China Time - Macau',
    countryName: 'Macao',
    dstOffset: 480,
  },
  'Asia/Shanghai': {
    name: 'Asia/Shanghai',
    offset: 480,
    alternativeName: 'China Time',
    raw: '+08:00 China Time - Shanghai, Beijing, Shenzhen, Guangzhou',
    countryName: 'China',
    dstOffset: 480,
  },
  'Asia/Hong_Kong': {
    name: 'Asia/Hong_Kong',
    offset: 480,
    alternativeName: 'Hong Kong Time',
    raw: '+08:00 Hong Kong Time - Hong Kong, Kowloon, Victoria, Tuen Mun',
    countryName: 'Hong Kong',
    dstOffset: 480,
  },
  'Asia/Irkutsk': {
    name: 'Asia/Irkutsk',
    offset: 480,
    alternativeName: 'Irkutsk Time',
    raw: '+08:00 Irkutsk Time - Irkutsk, Ulan-Ude, Bratsk, Angarsk',
    countryName: 'Russia',
    dstOffset: 480,
  },
  'Asia/Kuala_Lumpur': {
    name: 'Asia/Kuala_Lumpur',
    offset: 480,
    alternativeName: 'Malaysia Time',
    raw: '+08:00 Malaysia Time - Johor Bahru, Kota Bharu, Kuala Lumpur, Petaling Jaya',
    countryName: 'Malaysia',
    dstOffset: 480,
  },
  'Asia/Manila': {
    name: 'Asia/Manila',
    offset: 480,
    alternativeName: 'Philippine Time',
    raw: '+08:00 Philippine Time - Quezon City, Davao, Manila, Caloocan City',
    countryName: 'Philippines',
    dstOffset: 480,
  },
  'Asia/Singapore': {
    name: 'Asia/Singapore',
    offset: 480,
    alternativeName: 'Singapore Time',
    raw: '+08:00 Singapore Time - Singapore, Woodlands, Geylang, Queenstown Estate',
    countryName: 'Singapore',
    dstOffset: 480,
  },
  'Asia/Taipei': {
    name: 'Asia/Taipei',
    offset: 480,
    alternativeName: 'Taipei Time',
    raw: '+08:00 Taipei Time - Taipei, Kaohsiung, Taichung, Tainan',
    countryName: 'Taiwan',
    dstOffset: 480,
  },
  'Asia/Ulaanbaatar': {
    name: 'Asia/Ulaanbaatar',
    offset: 480,
    alternativeName: 'Ulaanbaatar Time',
    raw: '+08:00 Ulaanbaatar Time - Ulan Bator, Erdenet, Darhan, Mörön',
    countryName: 'Mongolia',
    dstOffset: 480,
  },
  'Australia/Eucla': {
    name: 'Australia/Eucla',
    offset: 525,
    alternativeName: 'Australian Central Western Time',
    raw: '+08:45 Australian Central Western Time - Eucla',
    countryName: 'Australia',
    dstOffset: 525,
  },
  'Asia/Dili': {
    name: 'Asia/Dili',
    offset: 540,
    alternativeName: 'East Timor Time',
    raw: '+09:00 East Timor Time - Dili, Maliana, Suai, Likisá',
    countryName: 'Timor Leste',
    dstOffset: 540,
  },
  'Asia/Jayapura': {
    name: 'Asia/Jayapura',
    offset: 540,
    alternativeName: 'Eastern Indonesia Time',
    raw: '+09:00 Eastern Indonesia Time - Jayapura, Ambon, Sorong, Ternate',
    countryName: 'Indonesia',
    dstOffset: 540,
  },
  'Asia/Tokyo': {
    name: 'Asia/Tokyo',
    offset: 540,
    alternativeName: 'Japan Time',
    raw: '+09:00 Japan Time - Tokyo, Yokohama, Osaka, Nagoya',
    countryName: 'Japan',
    dstOffset: 540,
  },
  'Asia/Pyongyang': {
    name: 'Asia/Pyongyang',
    offset: 540,
    alternativeName: 'Korean Time',
    raw: '+09:00 Korean Time - Pyongyang, Hamhŭng, Namp’o, Sunch’ŏn',
    countryName: 'North Korea',
    dstOffset: 540,
  },
  'Asia/Seoul': {
    name: 'Asia/Seoul',
    offset: 540,
    alternativeName: 'Korean Time',
    raw: '+09:00 Korean Time - Seoul, Busan, Incheon, Daegu',
    countryName: 'South Korea',
    dstOffset: 540,
  },
  'Pacific/Palau': {
    name: 'Pacific/Palau',
    offset: 540,
    alternativeName: 'Palau Time',
    raw: '+09:00 Palau Time - Ngerulmud',
    countryName: 'Palau',
    dstOffset: 540,
  },
  'Asia/Chita': {
    name: 'Asia/Chita',
    offset: 540,
    alternativeName: 'Yakutsk Time',
    raw: '+09:00 Yakutsk Time - Chita, Yakutsk, Blagoveshchensk, Belogorsk',
    countryName: 'Russia',
    dstOffset: 540,
  },
  'Australia/Darwin': {
    name: 'Australia/Darwin',
    offset: 570,
    alternativeName: 'Australian Central Time',
    raw: '+09:30 Australian Central Time - Darwin, Alice Springs, Palmerston',
    countryName: 'Australia',
    dstOffset: 570,
  },
  'Australia/Brisbane': {
    name: 'Australia/Brisbane',
    offset: 600,
    alternativeName: 'Australian Eastern Time',
    raw: '+10:00 Australian Eastern Time - Brisbane, Gold Coast, Logan City, Townsville',
    countryName: 'Australia',
    dstOffset: 600,
  },
  'Pacific/Guam': {
    name: 'Pacific/Guam',
    offset: 600,
    alternativeName: 'Chamorro Time',
    raw: '+10:00 Chamorro Time - Dededo Village, Yigo Village, Tamuning-Tumon-Harmon Village, Tamuning',
    countryName: 'Guam',
    dstOffset: 600,
  },
  'Pacific/Saipan': {
    name: 'Pacific/Saipan',
    offset: 600,
    alternativeName: 'Chamorro Time',
    raw: '+10:00 Chamorro Time - Saipan',
    countryName: 'Northern Mariana Islands',
    dstOffset: 600,
  },
  'Pacific/Chuuk': {
    name: 'Pacific/Chuuk',
    offset: 600,
    alternativeName: 'Chuuk Time',
    raw: '+10:00 Chuuk Time - Chuuk',
    countryName: 'Micronesia',
    dstOffset: 600,
  },
  'Antarctica/DumontDUrville': {
    name: 'Antarctica/DumontDUrville',
    offset: 600,
    alternativeName: 'Dumont-d’Urville Time',
    raw: '+10:00 Dumont-d’Urville Time - DumontDUrville',
    countryName: 'Antarctica',
    dstOffset: 600,
  },
  'Pacific/Port_Moresby': {
    name: 'Pacific/Port_Moresby',
    offset: 600,
    alternativeName: 'Papua New Guinea Time',
    raw: '+10:00 Papua New Guinea Time - Port Moresby, Lae, Mount Hagen, Popondetta',
    countryName: 'Papua New Guinea',
    dstOffset: 600,
  },
  'Asia/Vladivostok': {
    name: 'Asia/Vladivostok',
    offset: 600,
    alternativeName: 'Vladivostok Time',
    raw: '+10:00 Vladivostok Time - Khabarovsk, Vladivostok, Khabarovsk Vtoroy, Komsomolsk-on-Amur',
    countryName: 'Russia',
    dstOffset: 600,
  },
  'Australia/Adelaide': {
    name: 'Australia/Adelaide',
    offset: 570,
    alternativeName: 'Australian Central Time',
    raw: '+09:30 Australian Central Time - Adelaide, Adelaide Hills, Mount Gambier, Morphett Vale',
    countryName: 'Australia',
    dstOffset: 630,
  },
  'Australia/Sydney': {
    name: 'Australia/Sydney',
    offset: 600,
    alternativeName: 'Australian Eastern Time',
    raw: '+10:00 Australian Eastern Time - Sydney, Melbourne, Canberra, Newcastle',
    countryName: 'Australia',
    dstOffset: 660,
  },
  'Pacific/Bougainville': {
    name: 'Pacific/Bougainville',
    offset: 660,
    alternativeName: 'Bougainville Time',
    raw: '+11:00 Bougainville Time - Arawa',
    countryName: 'Papua New Guinea',
    dstOffset: 660,
  },
  'Antarctica/Casey': {
    name: 'Antarctica/Casey',
    offset: 660,
    alternativeName: 'Casey Time',
    raw: '+11:00 Casey Time - Casey',
    countryName: 'Antarctica',
    dstOffset: 660,
  },
  'Pacific/Kosrae': {
    name: 'Pacific/Kosrae',
    offset: 660,
    alternativeName: 'Kosrae Time',
    raw: '+11:00 Kosrae Time - Kosrae, Palikir - National Government Center',
    countryName: 'Micronesia',
    dstOffset: 660,
  },
  'Australia/Lord_Howe': {
    name: 'Australia/Lord_Howe',
    offset: 630,
    alternativeName: 'Lord Howe Time',
    raw: '+10:30 Lord Howe Time - Lord Howe',
    countryName: 'Australia',
    dstOffset: 660,
  },
  'Pacific/Noumea': {
    name: 'Pacific/Noumea',
    offset: 660,
    alternativeName: 'New Caledonia Time',
    raw: '+11:00 New Caledonia Time - Nouméa, Mont-Dore, Dumbéa',
    countryName: 'New Caledonia',
    dstOffset: 660,
  },
  'Asia/Sakhalin': {
    name: 'Asia/Sakhalin',
    offset: 660,
    alternativeName: 'Sakhalin Time',
    raw: '+11:00 Sakhalin Time - Yuzhno-Sakhalinsk, Magadan, Korsakov, Kholmsk',
    countryName: 'Russia',
    dstOffset: 660,
  },
  'Pacific/Guadalcanal': {
    name: 'Pacific/Guadalcanal',
    offset: 660,
    alternativeName: 'Solomon Islands Time',
    raw: '+11:00 Solomon Islands Time - Honiara',
    countryName: 'Solomon Islands',
    dstOffset: 660,
  },
  'Pacific/Efate': {
    name: 'Pacific/Efate',
    offset: 660,
    alternativeName: 'Vanuatu Time',
    raw: '+11:00 Vanuatu Time - Port-Vila',
    countryName: 'Vanuatu',
    dstOffset: 660,
  },
  'Pacific/Tarawa': {
    name: 'Pacific/Tarawa',
    offset: 720,
    alternativeName: 'Gilbert Islands Time',
    raw: '+12:00 Gilbert Islands Time - Tarawa',
    countryName: 'Kiribati',
    dstOffset: 720,
  },
  'Pacific/Majuro': {
    name: 'Pacific/Majuro',
    offset: 720,
    alternativeName: 'Marshall Islands Time',
    raw: '+12:00 Marshall Islands Time - Majuro, Kwajalein, RMI Capitol',
    countryName: 'Marshall Islands',
    dstOffset: 720,
  },
  'Pacific/Nauru': {
    name: 'Pacific/Nauru',
    offset: 720,
    alternativeName: 'Nauru Time',
    raw: '+12:00 Nauru Time - Yaren',
    countryName: 'Nauru',
    dstOffset: 720,
  },
  'Pacific/Norfolk': {
    name: 'Pacific/Norfolk',
    offset: 660,
    alternativeName: 'Norfolk Island Time',
    raw: '+11:00 Norfolk Island Time - Kingston',
    countryName: 'Norfolk Island',
    dstOffset: 720,
  },
  'Asia/Kamchatka': {
    name: 'Asia/Kamchatka',
    offset: 720,
    alternativeName: 'Petropavlovsk-Kamchatski Time',
    raw: '+12:00 Petropavlovsk-Kamchatski Time - Petropavlovsk-Kamchatsky, Yelizovo, Vilyuchinsk, Anadyr',
    countryName: 'Russia',
    dstOffset: 720,
  },
  'Pacific/Funafuti': {
    name: 'Pacific/Funafuti',
    offset: 720,
    alternativeName: 'Tuvalu Time',
    raw: '+12:00 Tuvalu Time - Funafuti',
    countryName: 'Tuvalu',
    dstOffset: 720,
  },
  'Pacific/Wake': {
    name: 'Pacific/Wake',
    offset: 720,
    alternativeName: 'Wake Island Time',
    raw: '+12:00 Wake Island Time - Wake',
    countryName: 'United States Minor Outlying Islands',
    dstOffset: 720,
  },
  'Pacific/Wallis': {
    name: 'Pacific/Wallis',
    offset: 720,
    alternativeName: 'Wallis & Futuna Time',
    raw: '+12:00 Wallis & Futuna Time - Mata-Utu',
    countryName: 'Wallis and Futuna',
    dstOffset: 720,
  },
  'Pacific/Apia': {
    name: 'Pacific/Apia',
    offset: 780,
    alternativeName: 'Apia Time',
    raw: '+13:00 Apia Time - Apia',
    countryName: 'Samoa',
    dstOffset: 840,
  },
  'Pacific/Fiji': {
    name: 'Pacific/Fiji',
    offset: 720,
    alternativeName: 'Fiji Time',
    raw: '+12:00 Fiji Time - Suva, Lautoka, Nadi, Labasa',
    countryName: 'Fiji',
    dstOffset: 780,
  },
  'Pacific/Auckland': {
    name: 'Pacific/Auckland',
    offset: 720,
    alternativeName: 'New Zealand Time',
    raw: '+12:00 New Zealand Time - Auckland, Wellington, Christchurch, Manukau City',
    countryName: 'New Zealand',
    dstOffset: 780,
  },
  'Antarctica/McMurdo': {
    name: 'Antarctica/McMurdo',
    offset: 720,
    alternativeName: 'New Zealand Time',
    raw: '+12:00 New Zealand Time - McMurdo',
    countryName: 'Antarctica',
    dstOffset: 780,
  },
  'Pacific/Kanton': {
    name: 'Pacific/Kanton',
    offset: 780,
    alternativeName: 'Phoenix Islands Time',
    raw: '+13:00 Phoenix Islands Time - Kanton',
    countryName: 'Kiribati',
    dstOffset: 780,
  },
  'Pacific/Fakaofo': {
    name: 'Pacific/Fakaofo',
    offset: 780,
    alternativeName: 'Tokelau Time',
    raw: '+13:00 Tokelau Time - Fakaofo',
    countryName: 'Tokelau',
    dstOffset: 780,
  },
  'Pacific/Tongatapu': {
    name: 'Pacific/Tongatapu',
    offset: 780,
    alternativeName: 'Tonga Time',
    raw: '+13:00 Tonga Time - Nuku‘alofa',
    countryName: 'Tonga',
    dstOffset: 780,
  },
  'Pacific/Chatham': {
    name: 'Pacific/Chatham',
    offset: 765,
    alternativeName: 'Chatham Time',
    raw: '+12:45 Chatham Time - Chatham',
    countryName: 'New Zealand',
    dstOffset: 825,
  },
  'Pacific/Kiritimati': {
    name: 'Pacific/Kiritimati',
    offset: 840,
    alternativeName: 'Line Islands Time',
    raw: '+14:00 Line Islands Time - Kiritimati',
    countryName: 'Kiribati',
    dstOffset: 840,
  },
};
