#!/bin/sh

print() {
  echo "    [PRECOMMIT]: $1" >&2
}

# `lint-staged` is great, but its' parsing capabilites of more advanced CLIs is poor.
# We can use it reliably only with programs that expect the following syntax:
#     command [options] [arg1] [arg2] [arg3] ...
# more sophisiticated checks should be done in this script without `lint-staged`.
print 'Running "lint-staged" ...'
yarn lint-staged

LOGFILE=.husky/log.txt
try() {
  if ! "$@" >"$LOGFILE" 2>&1; then
    print "Errors detected. Aborting commit."
    print "Error logs:\n"
    cat "$LOGFILE"
    exit 1
  fi
}

# Some precommit checks can take several seconds. Therefore, we
# want them to trigger only when relevant files are staged.
STAGED_FILES=$(git diff-index HEAD --cached --name-only)

print "Checking for changes in TypeScript source files..."
if echo "$STAGED_FILES" | grep "packages/react-native-calendar-kit/src/.*\.\(ts\|tsx\)$" --silent; then
  print "Running TypeScript checks..."

  try yarn workspace @howljs/calendar-kit type:check

  print "Success."
else
  print "No changes. Skipping TypeScript checks."
fi

print "All good, committing..."

exit 0
